-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 27, 2024 at 01:53 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.1.25

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `skind`
--

-- --------------------------------------------------------

--
-- Table structure for table `blogs`
--

CREATE TABLE `blogs` (
  `id` int(11) NOT NULL,
  `name` varchar(300) NOT NULL,
  `details1` varchar(2500) NOT NULL,
  `details2` varchar(2500) NOT NULL,
  `img` varchar(2500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `blogs`
--

INSERT INTO `blogs` (`id`, `name`, `details1`, `details2`, `img`) VALUES
(1, 'Acne and Rosacea', 'Acne:\r\n\r\nAcne is a common skin condition characterized by the presence of pimples, blackheads, whiteheads, and cysts on the face, neck, chest, back, and shoulders. It occurs when hair follicles become clogged with oil and dead skin cells, leading to inflammation and the formation of lesions. Acne is often associated with hormonal changes during puberty, but it can affect individuals of all ages.\r\n\r\nThere are several types of acne, including:\r\n\r\nComedonal Acne: Characterized by the presence of blackheads and whiteheads.\r\nInflammatory Acne: Involves red, swollen, and painful lesions, including papules, pustules, and nodules.\r\nCystic Acne: Deep, painful cysts that can lead to scarring if not treated promptly.\r\nTreatment for acne varies depending on its severity and type. Common treatment options include topical medications (such as benzoyl peroxide, salicylic acid, and retinoids), oral medications (such as antibiotics and isotretinoin), and in-office procedures (such as chemical peels, laser therapy, and extraction).\r\n\r\nRosacea:\r\n\r\nRosacea is a chronic skin condition characterized by facial redness, flushing, visible blood vessels, and acne-like bumps. It typically affects the central part of the face, including the cheeks, nose, chin, and forehead. Rosacea tends to worsen over time if left untreated and can lead to persistent redness and thickening of the skin.\r\n\r\nThere are several subtypes of rosacea, including:\r\n\r\nErythematotelangiectatic Rosacea: Characterized by facial redness, flushing, and visible blood vessels.\r\nPapulopustular Rosacea: Involves acne-like bumps and pus-filled lesions.\r\nPhymatous Rosacea: Causes thickening and enlargement of the skin, often leading to a bulbous nose (rhinophyma).\r\nTriggers for rosacea include sun exposure, hot or spicy foods, alcohol, stress, and certain skincare products. Treatment options for rosacea focus on managing symptoms and preventing flare-ups. These may include topical medications (such as metronidazole and azelaic acid), oral antibiotics, laser therapy, and lifestyle modifications to avoid triggers. Early diagnosis and treatment are crucial in managing both acne and rosacea effectively and minimizing long-term complications.', '', 'AcneRosacea.jpeg'),
(2, 'Actinic Keratosis', 'Actinic Keratosis (AK):\nActinic keratosis, also known as solar keratosis, is a precancerous skin condition caused by prolonged exposure to ultraviolet (UV) radiation from the sun. It typically appears as rough, scaly patches on sun-exposed areas of the skin, such as the face, scalp, ears, neck, arms, and hands. AKs are considered precursors to squamous cell carcinoma (SCC), a type of skin cancer.\n\nIf left untreated, actinic keratosis lesions may progress to squamous cell carcinoma over time. Therefore, early detection and treatment are essential in preventing the development of skin cancer. Treatment options for actinic keratosis include topical medications (such as fluorouracil, imiquimod, and diclofenac), cryotherapy (freezing), chemical peels, photodynamic therapy, and surgical removal.\n\nBasal Cell Carcinoma (BCC):\n\nBasal cell carcinoma is the most common type of skin cancer, accounting for the majority of skin cancer cases worldwide. It typically develops on areas of the skin that are frequently exposed to the sun, such as the face, head, neck, and hands. BCC usually appears as a shiny, pearly bump or a pinkish patch that may bleed or develop a crust.\n\nWhile basal cell carcinoma grows slowly and rarely metastasizes (spreads to other parts of the body), it can cause local tissue destruction if left untreated. Treatment options for basal cell carcinoma include surgical excision, Mohs micrographic surgery, cryotherapy, curettage and electrodessication, radiation therapy, and topical medications (such as imiquimod and 5-fluorouracil).\n\nOther Malignant Lesions:\n\nIn addition to actinic keratosis and basal cell carcinoma, there are several other types of malignant skin lesions that require attention and treatment:\n\nSquamous Cell Carcinoma (SCC): SCC is the second most common type of skin cancer. It arises from the squamous cells in the skin\'s outermost layer and often presents as a firm, red nodule or a scaly, crusty lesion. Treatment options for SCC include surgical excision, Mohs micrographic surgery, radiation therapy, and topical medications.\n\nMelanoma: Melanoma is the most aggressive form of skin cancer, arising from the pigment-producing cells called melanocytes. It can develop from existing moles or appear as new, abnormal growths on the skin. Melanoma may exhibit the ABCDE criteria (asymmetry, border irregularity, color variation, diameter greater than 6 mm, and evolving features). Early detection and surgical excision are crucial f', '', 'Actinic Keratosis Basal Cell Carcinoma and other Malignant Lesions.webp'),
(3, 'Atopic Dermatitis', 'Atopic dermatitis, also known as eczema, is a chronic inflammatory skin condition characterized by dry, itchy, red, and inflamed patches of skin. It is a common condition, particularly in children, but can persist into adulthood. Atopic dermatitis is believed to result from a combination of genetic, environmental, and immune system factors.\r\n\r\nThe hallmark symptom of atopic dermatitis is intense itching, which can be severe and disruptive to daily life. Scratching the affected areas can lead to skin damage, thickening, and increased risk of infection. The condition often presents in \"flare-ups,\" where symptoms worsen for a period before improving or resolving temporarily.\r\n\r\nThe exact cause of atopic dermatitis is not fully understood, but it is thought to involve a dysfunction in the skin barrier, leading to increased permeability and susceptibility to irritants and allergens. Additionally, immune system dysregulation plays a role in the inflammatory response seen in atopic dermatitis.\r\n\r\nManagement of atopic dermatitis focuses on relieving symptoms, preventing flare-ups, and maintaining skin hydration and integrity. Treatment options may include:\r\n\r\nEmollients and Moisturizers: Regular application of emollients and moisturizers helps to hydrate the skin and restore the skin barrier function, reducing dryness and itchiness.\r\n\r\nTopical Corticosteroids: Topical corticosteroids are often prescribed to reduce inflammation and itching during flare-ups. They are available in various strengths and formulations, depending on the severity of symptoms and the affected area.\r\n\r\nTopical Calcineurin Inhibitors: These medications, such as tacrolimus and pimecrolimus, help to suppress the immune response and reduce inflammation in the skin. They are commonly used in sensitive areas, such as the face and neck.\r\n\r\nAntihistamines: Oral antihistamines may be prescribed to relieve itching and improve sleep quality, particularly during nighttime flare-ups.\r\n\r\nAvoidance of Triggers: Identifying and avoiding triggers that exacerbate symptoms, such as certain fabrics, harsh soaps, environmental allergens, and stress, can help prevent flare-ups.\r\n\r\nPhototherapy: In some cases, ultraviolet (UV) light therapy may be recommended to reduce inflammation and improve symptoms, especially for individuals with moderate to severe atopic dermatitis.\r\n\r\nImmunomodulators: Systemic immunomodulatory medications, such as cyclosporine, methotrexate, or dupilumab, may be considered for individuals', '', 'Atopic Dermatitis.jpg'),
(4, 'Bullous Disease', 'Bullous diseases encompass a group of skin disorders characterized by the formation of fluid-filled blisters (bullae) on the skin or mucous membranes. These blisters vary in size and can occur anywhere on the body. Bullous diseases can be caused by a variety of factors, including genetic mutations, autoimmune reactions, infections, medications, and environmental triggers.\r\n\r\nOne of the most common types of bullous diseases is pemphigus, which includes several subtypes such as pemphigus vulgaris and pemphigus foliaceus. Pemphigus is an autoimmune disorder characterized by the production of autoantibodies that target proteins in the skin, leading to the formation of intraepidermal blisters. These blisters are fragile and prone to rupture, resulting in painful erosions and ulcers on the skin and mucous membranes.\r\n\r\nAnother common bullous disease is bullous pemphigoid, which primarily affects the elderly. Bullous pemphigoid is also an autoimmune condition but typically involves the formation of subepidermal blisters, which are located beneath the top layer of the skin (epidermis). The blisters are often large, tense, and less prone to rupture compared to those seen in pemphigus. Bullous pemphigoid may present with intense itching and widespread blistering, particularly on the trunk, extremities, and flexural areas.\r\n\r\nOther types of bullous diseases include dermatitis herpetiformis, epidermolysis bullosa, linear IgA bullous dermatosis, and erythema multiforme. These conditions have distinct clinical features, underlying mechanisms, and triggers, but they share the common characteristic of blister formation.\r\n\r\nTreatment for bullous diseases typically involves a combination of medications and supportive care aimed at controlling inflammation, preventing infection, and promoting wound healing. Common treatments may include corticosteroids, immunosuppressive agents, antihistamines, antibiotics, and topical wound care products. In severe cases, systemic therapies such as intravenous immunoglobulins (IVIG) or immunomodulatory medications may be required to manage symptoms and prevent complications.\r\n\r\nManagement of bullous diseases often requires a multidisciplinary approach involving dermatologists, immunologists, rheumatologists, and other healthcare professionals. Close monitoring and regular follow-up are essential to assess treatment response, monitor disease activity, and adjust therapeutic strategies as needed to optimize outcomes and improve quality of lif', '', 'Bullous Disease.jpeg'),
(5, 'Cellulitis Impetigo', '\r\nCellulitis, impetigo, and other bacterial skin infections are common dermatological conditions caused by various bacteria. These infections can range from mild and localized to severe and potentially life-threatening, depending on the causative organism, the extent of tissue involvement, and the individual\'s immune response.\r\n\r\nCellulitis is a bacterial infection of the deeper layers of the skin and subcutaneous tissue. It typically presents as redness, warmth, swelling, and tenderness in the affected area. Cellulitis can occur anywhere on the body but is most commonly found on the lower legs. Common bacteria responsible for cellulitis include Staphylococcus aureus and Streptococcus pyogenes. Treatment usually involves oral or intravenous antibiotics to eradicate the infection and prevent complications such as abscess formation and systemic spread.\r\n\r\nImpetigo is a superficial bacterial skin infection characterized by honey-colored crusts and vesicles. It is highly contagious and commonly affects children, particularly in warm and humid environments. Impetigo is typically caused by Staphylococcus aureus or Streptococcus pyogenes. Treatment involves topical or systemic antibiotics to eliminate the bacteria and promote healing. Good hygiene practices and prompt treatment of skin lesions can help prevent the spread of impetigo to others.\r\n\r\nOther bacterial skin infections include folliculitis, furuncles (boils), and carbuncles, which affect hair follicles and deeper skin layers. These infections often result from bacterial colonization of hair follicles, leading to inflammation, pain, and the formation of pus-filled lesions. Treatment may involve warm compresses, topical antibiotics, or incision and drainage for more severe cases.\r\n\r\nErysipelas is a type of cellulitis characterized by well-defined, raised borders and rapid progression. It is caused by Streptococcus pyogenes and typically affects the face and lower extremities. Prompt antibiotic treatment is essential to prevent complications such as systemic infection and necrotizing fasciitis.\r\n\r\nNecrotizing fasciitis is a severe bacterial infection that involves the deeper layers of the skin, subcutaneous tissue, and fascia. It is characterized by rapid tissue destruction, severe pain, and systemic symptoms such as fever and malaise. Necrotizing fasciitis requires urgent surgical intervention, along with broad-spectrum antibiotics, to remove infected tissue and prevent further spread.\r\n\r\nOverall, prompt r', '', 'Cellulitis Impetigo and other Bacterial Infections.jpg'),
(6, 'Eczema', 'atGPT\r\nEczema, also known as atopic dermatitis, is a chronic inflammatory skin condition characterized by dry, itchy, red, and inflamed patches of skin. It is a common condition, affecting people of all ages, but it is particularly prevalent in infants and children. Eczema is believed to result from a combination of genetic, environmental, and immune system factors.\r\n\r\nThe exact cause of eczema is not fully understood, but it is thought to involve a dysfunction in the skin barrier, leading to increased permeability and susceptibility to irritants and allergens. Additionally, immune system dysregulation plays a role in the inflammatory response seen in eczema.\r\n\r\nThe hallmark symptom of eczema is intense itching, which can be severe and disruptive to daily life. Scratching the affected areas can lead to skin damage, thickening, and increased risk of infection. The condition often presents in \"flare-ups,\" where symptoms worsen for a period before improving or resolving temporarily.\r\n\r\nEczema can vary in severity from mild, with occasional itching and redness, to severe, with widespread inflammation and persistent symptoms. It can also occur in specific patterns on the body, such as the face, hands, elbows, and knees.\r\n\r\nManagement of eczema focuses on relieving symptoms, preventing flare-ups, and maintaining skin hydration and integrity. Treatment options may include:\r\n\r\nEmollients and moisturizers: Regular application of emollients and moisturizers helps to hydrate the skin and restore the skin barrier function, reducing dryness and itchiness.\r\n\r\nTopical corticosteroids: Topical corticosteroids are often prescribed to reduce inflammation and itching during flare-ups. They are available in various strengths and formulations, depending on the severity of symptoms and the affected area.\r\n\r\nTopical calcineurin inhibitors: These medications, such as tacrolimus and pimecrolimus, help to suppress the immune response and reduce inflammation in the skin. They are commonly used in sensitive areas, such as the face and neck.\r\n\r\nAntihistamines: Oral antihistamines may be prescribed to relieve itching and improve sleep quality, particularly during nighttime flare-ups.\r\n\r\nAvoidance of triggers: Identifying and avoiding triggers that exacerbate symptoms, such as certain fabrics, harsh soaps, environmental allergens, and stress, can help prevent flare-ups.\r\n\r\nPhototherapy: In some cases, ultraviolet (UV) light therapy may be recommended to reduce inflammation and improve s', '', 'Eczema.webp'),
(7, 'Exanthems and Drug Eruptions', '\r\nExanthems and drug eruptions are skin conditions characterized by rash-like eruptions on the skin. While they share similarities in their presentation, they have distinct causes and management approaches.\r\n\r\nExanthems refer to widespread skin rashes that are typically caused by viral infections. Common examples include measles, rubella (German measles), chickenpox, and fifth disease (erythema infectiosum). These rashes often present with characteristic patterns and symptoms associated with the underlying viral infection. For instance, measles exanthem typically begins as small red spots that gradually merge to form larger blotchy patches, accompanied by fever, cough, runny nose, and conjunctivitis. Treatment for viral exanthems focuses on managing symptoms and providing supportive care, such as rest, hydration, and fever-reducing medications. In some cases, antiviral medications may be prescribed to shorten the duration of the infection.\r\n\r\nDrug eruptions, on the other hand, are skin reactions triggered by medications or other substances. These eruptions can manifest as various types of rashes, including maculopapular eruptions, urticaria (hives), erythema multiforme, and Stevens-Johnson syndrome/toxic epidermal necrolysis (SJS/TEN). Drug eruptions can result from allergic reactions, direct toxicity, or other immune-mediated mechanisms. The onset and severity of drug eruptions vary depending on the individual\'s sensitivity to the medication, the type of medication involved, and other factors such as dose and duration of exposure. Treatment for drug eruptions involves discontinuing the offending medication and providing supportive care to alleviate symptoms. In cases of severe or life-threatening reactions, such as SJS/TEN, hospitalization and intensive medical management are necessary.\r\n\r\nIn summary, while exanthems and drug eruptions both present as skin rashes, they have different underlying causes and management strategies. Exanthems are typically viral in origin and are managed by treating the underlying infection, while drug eruptions result from medications or other substances and require discontinuation of the offending agent and supportive care. Prompt recognition and appropriate management are essential in both conditions to prevent complications and promote recovery.', '', 'Exanthems and Drug Eruptions.jpg'),
(8, 'Alopecia and other Hair diseases', 'Hair loss, also known as alopecia, can result from various factors and present in different patterns and forms. Understanding the underlying causes and characteristics of hair loss is essential for accurate diagnosis and effective management.\r\n\r\nAlopecia areata is a common autoimmune condition characterized by patchy hair loss on the scalp or other hair-bearing areas of the body. It occurs when the body\'s immune system mistakenly attacks hair follicles, leading to hair loss. Alopecia areata can manifest as small, round bald patches or more extensive hair loss involving larger areas of the scalp or body. While the exact cause of alopecia areata is unknown, genetic and environmental factors are believed to play a role. Treatment options may include corticosteroid injections, topical immunotherapy, and oral medications to suppress the immune response and promote hair regrowth.\r\n\r\nAndrogenetic alopecia, also known as male-pattern or female-pattern baldness, is the most common form of hair loss, affecting both men and women. It is characterized by gradual thinning of hair over the scalp, typically starting at the temples or crown in men and the central parting in women. Androgenetic alopecia is hereditary and is influenced by hormones, particularly dihydrotestosterone (DHT), which can shrink hair follicles and shorten the hair growth cycle. Treatment options may include topical minoxidil (Rogaine), oral finasteride (Propecia), low-level laser therapy, and hair transplantation surgery.\r\n\r\nOther hair diseases include telogen effluvium, a condition characterized by excessive shedding of hair due to stress, illness, hormonal changes, or medication use. Trichotillomania is a psychological disorder characterized by compulsive hair pulling, leading to hair loss and bald patches. Cicatricial alopecia, or scarring alopecia, results from inflammation or destruction of hair follicles, leading to permanent hair loss and scarring of the scalp.\r\n\r\nDiagnosis of hair diseases involves a thorough medical history, physical examination, and sometimes additional tests such as blood tests, scalp biopsies, or trichoscopy (hair microscopy). Treatment approaches vary depending on the underlying cause and may include addressing underlying medical conditions, lifestyle modifications, medication, and cosmetic interventions. Early diagnosis and intervention can help prevent further hair loss and promote hair regrowth, improving the overall quality of life for affected individuals.\r\n\r\n\r\n\r\n', '', 'Hair Loss Photos Alopecia and other Hair Diseases.webp'),
(9, 'Herpes HPV and other STDs', 'Sexually transmitted diseases (STDs), also known as sexually transmitted infections (STIs), are infections spread through sexual contact, including vaginal, anal, and oral sex. These infections can be caused by bacteria, viruses, or parasites and can have serious health consequences if left untreated. Common STDs include herpes, human papillomavirus (HPV), chlamydia, gonorrhea, syphilis, and HIV/AIDS.\r\n\r\nHerpes simplex virus (HSV) is a common viral infection that causes genital herpes, characterized by painful blisters or sores on the genitals or surrounding areas. HSV can also cause oral herpes, commonly known as cold sores or fever blisters. The virus is highly contagious and can be transmitted through sexual contact, even when no symptoms are present. While there is no cure for herpes, antiviral medications can help manage symptoms and reduce the frequency and severity of outbreaks.\r\n\r\nHuman papillomavirus (HPV) is a group of viruses that can infect the genital area, mouth, and throat. HPV is the most common sexually transmitted infection worldwide. While most HPV infections resolve on their own without causing symptoms or health problems, certain strains of the virus can cause genital warts and increase the risk of cervical, anal, penile, and throat cancers. Vaccines are available to protect against the most common cancer-causing strains of HPV, and regular screenings, such as Pap tests and HPV tests, can help detect abnormal changes early and prevent cancer.\r\n\r\nOther STDs, such as chlamydia, gonorrhea, and syphilis, are bacterial infections that can cause a range of symptoms, including genital discharge, pain during urination, and genital sores or ulcers. These infections can lead to serious complications if left untreated, including pelvic inflammatory disease (PID), infertility, and increased risk of HIV transmission. Prompt diagnosis and treatment with antibiotics are essential to prevent complications and reduce the spread of these infections.\r\n\r\nPrevention of STDs involves practicing safe sex, including consistent and correct condom use, limiting the number of sexual partners, and getting vaccinated against HPV. Routine STD screening and testing are recommended for sexually active individuals to detect infections early and prevent transmission to others. Open communication with sexual partners and healthcare providers is crucial in preventing and managing STDs and promoting sexual health and well-being.', '', 'Herpes HPV and other STDs.png'),
(10, 'Melasma', 'Light diseases and disorders of pigmentation encompass a wide range of conditions affecting the skin\'s coloration and response to light exposure. These conditions can be congenital or acquired and may result from genetic, environmental, or systemic factors.\r\n\r\nOne common condition is albinism, a genetic disorder characterized by a lack of melanin pigment in the skin, hair, and eyes. Individuals with albinism have very pale skin, light-colored hair, and often experience vision problems due to the absence of melanin in the retina. Albinism is caused by mutations in genes involved in melanin production and can result in increased sensitivity to sunlight and a higher risk of sunburn and skin cancer.\r\n\r\nVitiligo is another pigmentary disorder characterized by the loss of melanocytes, the pigment-producing cells, resulting in depigmented patches on the skin. The exact cause of vitiligo is unknown, but it is believed to involve autoimmune, genetic, and environmental factors. Vitiligo can occur at any age and may progress over time, causing significant emotional distress and impacting quality of life. Treatment options for vitiligo include topical corticosteroids, phototherapy, and surgical interventions such as skin grafting or melanocyte transplantation.\r\n\r\nHyperpigmentation disorders involve the overproduction or accumulation of melanin pigment in the skin, leading to darkened patches or spots. Common examples include melasma, post-inflammatory hyperpigmentation, and lentigines (age spots). These conditions can be triggered by sun exposure, hormonal changes, inflammation, or medication use. Treatment options for hyperpigmentation may include topical depigmenting agents, chemical peels, laser therapy, and cosmetic camouflage techniques.\r\n\r\nHypopigmentation disorders involve the loss or reduction of melanin pigment in the skin, resulting in lighter or white patches. Conditions such as pityriasis alba, tinea versicolor, and hypopigmented mycosis fungoides can cause hypopigmented lesions on the skin. Treatment may include antifungal medications, topical corticosteroids, and phototherapy, depending on the underlying cause.\r\n\r\nOverall, light diseases and disorders of pigmentation can have significant physical and psychological impacts on affected individuals. Early diagnosis and appropriate management are essential in minimizing symptoms, preventing complications, and improving the quality of life for individuals living with these conditions.', '', 'Light Diseases and Disorders of Pigmentation.jpg'),
(11, 'Lupus and Tissue diseases', '\r\nLupus and other connective tissue diseases (CTDs) are a group of autoimmune disorders that affect various organs and tissues in the body, including the skin, joints, kidneys, heart, lungs, and blood vessels. These conditions occur when the body\'s immune system mistakenly attacks its tissues, leading to inflammation, tissue damage, and dysfunction. Lupus, also known as systemic lupus erythematosus (SLE), is one of the most well-known CTDs, but there are several others, including rheumatoid arthritis (RA), systemic sclerosis (scleroderma), Sjögren\'s syndrome, and dermatomyositis.\r\n\r\nSystemic lupus erythematosus (SLE) is a chronic autoimmune disease characterized by a wide range of symptoms that can affect multiple organs and systems. Common symptoms of lupus include fatigue, joint pain and swelling, skin rashes (such as the classic butterfly rash), fever, chest pain, and photosensitivity. Lupus is a complex and heterogeneous disease with a fluctuating course, and its severity and manifestations vary widely among individuals. Treatment for lupus typically involves a combination of medications to control inflammation, manage symptoms, and prevent complications. Immunosuppressive drugs, corticosteroids, antimalarial medications, and biologic therapies may be used depending on the severity of the disease and the organs affected.\r\n\r\nRheumatoid arthritis (RA) is another common CTD characterized by chronic inflammation of the joints, leading to pain, swelling, stiffness, and progressive joint damage. RA can also affect other organs, including the skin, eyes, heart, and lungs. Treatment for RA aims to reduce inflammation, alleviate symptoms, and prevent joint damage. Medications such as disease-modifying antirheumatic drugs (DMARDs), nonsteroidal anti-inflammatory drugs (NSAIDs), corticosteroids, and biologic agents are commonly used to manage RA.\r\n\r\nOther CTDs, such as systemic sclerosis (scleroderma), Sjögren\'s syndrome, and dermatomyositis, have distinct clinical features and underlying mechanisms but share similarities in autoimmune pathogenesis. These conditions can affect various organs and tissues, leading to a range of symptoms and complications. Treatment for CTDs involves a multidisciplinary approach, including medications, physical therapy, occupational therapy, and lifestyle modifications to manage symptoms, prevent organ damage, and improve quality of life. Early diagnosis and appropriate management are crucial in controlling disease activity and mini', '', 'Lupus and other Connective Tissue diseases.jpg'),
(12, 'Melanoma Skin Cancer Nevi', 'Melanoma, skin cancer, nevi, and moles are all related to the skin and can have significant implications for health and well-being. Melanoma is the most serious type of skin cancer, arising from the uncontrolled growth of melanocytes, the pigment-producing cells in the skin. Melanoma can develop from existing moles or appear as new, abnormal growths on the skin. It is often characterized by changes in the size, shape, color, or texture of moles or other pigmented lesions. Early detection and treatment of melanoma are crucial for improving outcomes and reducing the risk of metastasis (spread) to other parts of the body.\r\n\r\nNevi, commonly known as moles, are benign growths on the skin composed of clusters of melanocytes. Most moles are harmless and do not require treatment unless they exhibit suspicious features or changes over time. While moles are typically brown or black in color and have a round or oval shape, they can vary in size, shape, and color. Some moles may be present at birth (congenital nevi), while others may develop later in life due to sun exposure or genetic factors.\r\n\r\nRegular self-examinations of the skin and moles are important for detecting changes that may indicate melanoma or other skin cancers. The ABCDE rule can help individuals identify potentially suspicious moles:\r\n\r\nA - Asymmetry: One half of the mole does not match the other half.\r\nB - Border irregularity: The edges of the mole are irregular, blurred, or poorly defined.\r\nC - Color variation: The mole has uneven coloring or multiple colors (e.g., shades of brown, black, red, or blue).\r\nD - Diameter: The diameter of the mole is larger than 6 millimeters (about the size of a pencil eraser).\r\nE - Evolution: The mole is changing in size, shape, color, or texture over time.\r\n\r\nIf any of these features are present or if a mole exhibits other concerning characteristics (such as itching, bleeding, or crusting), it is important to consult a dermatologist for further evaluation and possible biopsy. Early detection and prompt treatment of melanoma and other skin cancers can significantly improve prognosis and reduce morbidity and mortality associated with these diseases. Additionally, practicing sun safety measures, such as wearing sunscreen, protective clothing, and avoiding tanning beds, can help reduce the risk of developing melanoma and other skin cancers.', '', 'melanoma.jpeg.jpg'),
(13, 'Nail Fungus', 'Nail fungus, also known as onychomycosis, is a common fungal infection that affects the nails, particularly the toenails. It is caused by dermatophyte fungi, yeasts, or molds that invade the nail bed and nail plate, leading to thickened, discolored, brittle, and crumbly nails. Nail fungus can be unsightly and uncomfortable, and if left untreated, it can cause pain, discomfort, and complications such as secondary bacterial infections.\r\n\r\nNail fungus typically thrives in warm, moist environments, making the feet, particularly the toenails, susceptible to infection. Factors that increase the risk of developing nail fungus include wearing tight or ill-fitting shoes, walking barefoot in public places such as locker rooms and swimming pools, having a weakened immune system, and having a history of nail trauma or injury.\r\n\r\nTreatment for nail fungus may include topical antifungal medications, oral antifungal medications, or a combination of both. Topical treatments, such as antifungal nail lacquers or creams, are applied directly to the affected nails and may be effective for mild to moderate cases of nail fungus. Oral antifungal medications, such as terbinafine or itraconazole, are taken by mouth and are often prescribed for more severe or persistent infections.\r\n\r\nIn addition to nail fungus, other common nail diseases and disorders include:\r\n\r\nNail psoriasis: Psoriasis is a chronic autoimmune condition that can affect the skin, nails, and joints. Nail psoriasis can cause pitting, discoloration, thickening, and crumbling of the nails. Treatment may include topical corticosteroids, phototherapy, or systemic medications to manage symptoms and prevent complications.\r\n\r\nOnycholysis: Onycholysis is the separation of the nail plate from the nail bed, resulting in a gap between the two. It can be caused by trauma, fungal infections, psoriasis, or contact dermatitis. Treatment depends on the underlying cause and may include addressing the contributing factors, such as avoiding trauma or treating fungal infections.\r\n\r\nIngrown toenails: Ingrown toenails occur when the edge of the nail grows into the surrounding skin, causing pain, swelling, and inflammation. Ingrown toenails can result from improper nail trimming, tight-fitting shoes, trauma, or genetics. Treatment may involve soaking the affected toe in warm water, gently lifting the nail edge, and wearing properly fitted footwear. In severe cases, surgical removal of the ingrown portion of the nail may be necessary.\r\n\r\n', '', 'nail fungus and other nail disease.jpeg.jpg'),
(14, 'Poison Ivy Photos', 'Contact dermatitis is a common skin condition characterized by inflammation and irritation of the skin resulting from contact with allergens or irritants. One well-known example of contact dermatitis is poison ivy, a plant that contains urushiol oil, a potent allergen that can cause a rash upon contact with the skin. Poison ivy rash typically presents as redness, swelling, itching, and the formation of fluid-filled blisters in the affected area. The rash may appear linear or streaky, following the pattern of contact with the plant\'s leaves, stems, or roots. Treatment for poison ivy rash includes washing the affected area with soap and water to remove any remaining urushiol oil, applying calamine lotion or hydrocortisone cream to reduce itching and inflammation, and taking oral antihistamines to alleviate symptoms.\r\n\r\nOther common causes of contact dermatitis include:\r\n\r\nPoison oak: Like poison ivy, poison oak contains urushiol oil and can cause a similar rash upon contact with the skin. The rash may appear similar to poison ivy rash and usually requires the same treatment approach.\r\n\r\nPoison sumac: Poison sumac is another plant that contains urushiol oil and can cause a rash upon contact. The rash from poison sumac may be more severe and widespread compared to poison ivy or poison oak rash. Treatment typically involves washing the affected area, applying topical corticosteroids, and taking oral antihistamines to relieve itching and inflammation.\r\n\r\nAllergic contact dermatitis: Allergic contact dermatitis occurs when the skin comes into contact with allergens such as metals (e.g., nickel), fragrances, preservatives, or latex. The rash may develop hours to days after exposure and can range from mild redness and itching to severe blistering and swelling. Treatment involves identifying and avoiding the allergen, using topical corticosteroids or antihistamines to relieve symptoms, and taking steps to prevent future exposure.\r\n\r\nIrritant contact dermatitis: Irritant contact dermatitis occurs when the skin is exposed to irritants such as soaps, detergents, solvents, or chemicals. The rash typically develops shortly after exposure and may be characterized by redness, burning, and stinging. Treatment involves removing the irritant, washing the affected area with mild soap and water, and applying moisturizers or barrier creams to protect the skin.\r\n\r\nOverall, contact dermatitis can be uncomfortable and disruptive, but with prompt identification and appropriate treat', '', 'poison ivy and other contact dermities.jpeg.jpg'),
(15, 'Psoriasis', 'Psoriasis, lichen planus, and related diseases are inflammatory skin conditions that can cause discomfort and affect quality of life for those affected. Psoriasis is a chronic autoimmune disorder characterized by the rapid turnover of skin cells, resulting in the formation of thick, red, scaly plaques on the skin\'s surface. These plaques may appear anywhere on the body but are commonly found on the scalp, elbows, knees, and lower back. Psoriasis can also affect the nails, causing pitting, discoloration, and thickening.\r\n\r\nLichen planus is an inflammatory skin condition characterized by the development of itchy, flat-topped papules or lesions on the skin, mucous membranes, or nails. The lesions of lichen planus are typically purple, polygonal in shape, and may have a fine white scale. Lichen planus can affect various parts of the body, including the wrists, ankles, lower back, genital area, mouth, and nails. In addition to skin involvement, lichen planus can also affect the mucous membranes, leading to oral lichen planus, which manifests as white, lacy patches or sores inside the mouth.\r\n\r\nOther related diseases include:\r\n\r\nPityriasis rosea: Pityriasis rosea is a common, benign skin condition characterized by the sudden onset of pink, scaly patches on the skin, followed by the appearance of a larger, oval-shaped lesion called a \"herald patch.\" Pityriasis rosea typically affects the trunk and may be accompanied by mild itching. The condition usually resolves on its own within a few weeks to months.\r\n\r\nSeborrheic dermatitis: Seborrheic dermatitis is a chronic inflammatory condition that affects areas of the skin with a high density of sebaceous glands, such as the scalp, face, and upper chest. It is characterized by redness, greasy scales, and itching. Seborrheic dermatitis can be exacerbated by factors such as stress, hormonal changes, and certain medications.\r\n\r\nEczema: Eczema, also known as atopic dermatitis, is a chronic inflammatory skin condition characterized by dry, itchy, red, and inflamed patches of skin. It often presents in \"flare-ups\" and may be triggered by factors such as allergens, irritants, stress, and weather changes.\r\n\r\nManagement of psoriasis, lichen planus, and related diseases typically involves a combination of topical treatments, phototherapy, systemic medications, and lifestyle modifications. Treatment aims to alleviate symptoms, reduce inflammation, and prevent disease progression, while improving the overall quality of life for aff', '', 'Psoriasis pictures Lichen Planus and related diseases.jpeg.jpg'),
(16, 'Scabies Lyme Disease', 'Scabies, Lyme disease, and other infestations and bites are conditions caused by various parasites, bacteria, or insects that can affect the skin and overall health of individuals.\r\n\r\nScabies is a contagious skin infestation caused by the Sarcoptes scabiei mite. It is characterized by intense itching and a pimple-like rash, which is often more severe at night. Scabies mites burrow into the skin, laying eggs and causing an allergic reaction that leads to inflammation and itching. Scabies is typically spread through close physical contact with an infected person, and outbreaks can occur in crowded living conditions, such as nursing homes, prisons, and childcare settings. Treatment for scabies involves topical medications, such as permethrin or ivermectin, to kill the mites and their eggs, as well as washing bedding and clothing in hot water to prevent reinfestation.\r\n\r\nLyme disease is a bacterial infection caused by the Borrelia burgdorferi bacterium, which is transmitted to humans through the bite of infected black-legged ticks. Early symptoms of Lyme disease may include a characteristic \"bull\'s-eye\" rash (erythema migrans), flu-like symptoms, joint pain, and fatigue. If left untreated, Lyme disease can lead to more severe symptoms, including neurological problems, joint inflammation, and heart palpitations. Treatment for Lyme disease involves antibiotics, such as doxycycline, amoxicillin, or cefuroxime, depending on the stage of the infection.\r\n\r\nOther infestations and bites that can affect the skin include:\r\n\r\nBed bugs: Bed bugs are small, reddish-brown insects that feed on human blood. Their bites can cause itching, redness, and swelling, and may result in a rash or localized allergic reaction. Treatment for bed bug infestations typically involves professional pest control measures, as well as washing bedding and clothing in hot water.\r\n\r\nFleas: Flea bites can cause itching, redness, and small, raised bumps on the skin. In addition to bites, flea infestations can also lead to allergic reactions and transmit diseases such as typhus and plague. Treatment for flea bites and infestations may include topical corticosteroids, antihistamines, and flea control measures for pets and the home environment.\r\n\r\nTick bites: Tick bites can transmit various diseases, including Lyme disease, Rocky Mountain spotted fever, and ehrlichiosis. Prompt removal of ticks and monitoring for symptoms of tick-borne illnesses are essential for early diagnosis and treatment. Tick-born', '', 'Scabies Lyme Disease and other Infestations and Bites.jpeg.jpg'),
(17, 'Seborrheic Keratoses', '\r\nSeborrheic keratoses (SKs) are common benign tumors of the skin that typically appear as raised, wart-like growths with a waxy, stuck-on appearance. They are often brown, black, or tan in color and may range in size from a few millimeters to several centimeters in diameter. Seborrheic keratoses are more common in older adults and tend to develop on areas of the skin exposed to sunlight, such as the face, neck, chest, and back.\r\n\r\nWhile seborrheic keratoses are benign and generally harmless, they can be cosmetically bothersome or cause irritation if they rub against clothing or jewelry. Treatment options for seborrheic keratoses may include cryotherapy (freezing), curettage (scraping), electrocautery (burning), or laser therapy to remove the growths. However, treatment is usually elective and may not be necessary unless the lesions are causing symptoms or aesthetic concerns.\r\n\r\nOther common benign tumors of the skin include:\r\n\r\nDermatofibromas: Dermatofibromas are small, firm, raised nodules that typically appear on the extremities, such as the legs. They may be pink, brown, or reddish in color and often have a dimpled or \"dimple sign\" appearance when squeezed from the sides. Dermatofibromas are benign and do not require treatment unless they cause symptoms or aesthetic concerns.\r\n\r\nLipomas: Lipomas are soft, doughy, movable lumps made up of fat cells that develop beneath the skin. They are typically painless and can occur anywhere on the body. Lipomas are benign and usually do not require treatment unless they grow large enough to cause discomfort or interfere with movement.\r\n\r\nNeurofibromas: Neurofibromas are benign tumors that arise from nerve tissue and can occur in isolation or as part of neurofibromatosis, a genetic disorder characterized by multiple neurofibromas and other symptoms. Neurofibromas may appear as soft, rubbery nodules or may be deeper and firmer in consistency. Treatment for neurofibromas may involve surgical excision for symptomatic or cosmetically bothersome lesions.\r\n\r\nWhile benign tumors of the skin are generally harmless, any new or changing growth should be evaluated by a dermatologist to rule out malignancy and determine the appropriate course of management. Regular skin examinations and monitoring of existing lesions are important for early detection and treatment of skin conditions.', '', 'Seborrheic Keratoses and other Benign Tumors.jpeg.jpg'),
(18, 'Systemic Disease', 'Systemic diseases, also known as systemic disorders or systemic illnesses, are medical conditions that affect multiple organ systems or the entire body rather than being localized to a specific organ or tissue. These diseases can have diverse causes, including genetic factors, infections, autoimmune reactions, environmental exposures, and lifestyle factors. Systemic diseases often involve complex interactions between genetic predisposition, immune dysregulation, and environmental triggers.\r\n\r\nExamples of systemic diseases include:\r\n\r\nDiabetes mellitus: Diabetes mellitus is a chronic metabolic disorder characterized by high blood sugar levels resulting from inadequate insulin production, impaired insulin action, or both. Diabetes can affect multiple organ systems, including the eyes, kidneys, nerves, heart, and blood vessels, leading to complications such as diabetic retinopathy, nephropathy, neuropathy, cardiovascular disease, and stroke.\r\n\r\nRheumatoid arthritis: Rheumatoid arthritis (RA) is a chronic autoimmune inflammatory disorder that primarily affects the joints but can also involve other organs and tissues. RA causes inflammation, pain, swelling, and stiffness in the joints, leading to progressive joint damage and disability if left untreated. In addition to joint involvement, RA can affect the skin, eyes, lungs, heart, and blood vessels.\r\n\r\nSystemic lupus erythematosus: Systemic lupus erythematosus (SLE) is a chronic autoimmune disease that can affect multiple organ systems, including the skin, joints, kidneys, heart, lungs, and nervous system. SLE is characterized by the production of autoantibodies that target the body\'s own tissues, leading to inflammation, tissue damage, and a wide range of symptoms, such as joint pain, fatigue, rash, fever, and organ dysfunction.\r\n\r\nCrohn\'s disease and ulcerative colitis: Crohn\'s disease and ulcerative colitis are chronic inflammatory bowel diseases (IBD) characterized by inflammation of the gastrointestinal tract. These conditions can cause abdominal pain, diarrhea, rectal bleeding, weight loss, and fatigue. In addition to gastrointestinal symptoms, IBD can affect other organs and systems, leading to complications such as arthritis, skin problems, eye inflammation, and liver disease.\r\n\r\nTreatment for systemic diseases often involves a multidisciplinary approach, including medications to manage symptoms and prevent complications, lifestyle modifications, such as diet and exercise, and regular monitoring and fol', '', 'Systemic Disease.jpeg.jpg'),
(19, 'Tinea Ringworm Candidiasis', 'Fungal infections, including tinea (ringworm), candidiasis, and other fungal infections, are common skin conditions caused by various types of fungi. These infections can affect different parts of the body, including the skin, nails, hair, and mucous membranes, and can range from mild and superficial to severe and invasive.\r\n\r\nTinea, commonly known as ringworm, refers to a group of fungal infections that affect the skin, scalp, and nails. Despite its name, ringworm is not caused by a worm but by various species of dermatophyte fungi. Ringworm infections typically present as red, scaly, circular patches on the skin, which may be itchy or painful. The lesions may have a raised, ring-shaped border with clearer skin in the center, giving them a characteristic appearance. Treatment for tinea infections usually involves antifungal medications, such as topical creams, lotions, or oral medications, depending on the severity and location of the infection.\r\n\r\nCandidiasis, also known as yeast infection, is caused by the overgrowth of Candida species of yeast, most commonly Candida albicans. Candidiasis can affect the skin, mouth (oral thrush), throat, genitals (vaginal yeast infection), and other mucous membranes. Symptoms of candidiasis may include redness, itching, swelling, and white, curd-like discharge in affected areas. Treatment for candidiasis typically involves antifungal medications, such as topical creams, suppositories, or oral medications, depending on the site and severity of the infection.\r\n\r\nOther fungal infections include:\r\n\r\nAthlete\'s foot (tinea pedis): Athlete\'s foot is a fungal infection of the feet, typically characterized by itching, burning, cracking, and scaling of the skin between the toes or on the soles of the feet. It is commonly spread in warm, moist environments such as locker rooms and swimming pools.\r\n\r\nOnychomycosis: Onychomycosis is a fungal infection of the nails, most commonly affecting the toenails. It can cause thickening, discoloration, and crumbling of the nails, leading to cosmetic and functional concerns. Treatment for onychomycosis may involve topical or oral antifungal medications and, in severe cases, surgical removal of the affected nail.\r\n\r\nOral candidiasis (thrush): Oral thrush is a fungal infection of the mouth and throat caused by Candida yeast. It can present as white, creamy patches on the tongue, inner cheeks, gums, or throat, often accompanied by discomfort or pain. Treatment typically involves antifungal medicat', '', 'ringworm.jpeg.jpg');
INSERT INTO `blogs` (`id`, `name`, `details1`, `details2`, `img`) VALUES
(20, 'Urticaria Hives', 'Urticaria, commonly known as hives, is a skin condition characterized by the sudden onset of raised, red, and itchy welts or bumps on the skin. Hives can vary in size and shape and may appear anywhere on the body. They typically resolve within a few hours to days but may recur or persist for longer periods in some cases. Urticaria is a common condition, affecting up to 20% of the population at some point in their lives.\r\n\r\nThe underlying cause of urticaria is often unknown, but it is believed to involve a complex interplay of immune, inflammatory, and environmental factors. Acute urticaria is often triggered by allergens, such as certain foods (e.g., nuts, shellfish, eggs), medications (e.g., antibiotics, aspirin, NSAIDs), insect stings or bites, latex, pollen, or viral infections. Physical stimuli, such as pressure, cold, heat, sunlight, or exercise, can also trigger hives in some individuals.\r\n\r\nChronic urticaria, on the other hand, persists for more than six weeks and may be associated with underlying medical conditions, such as autoimmune disorders, thyroid disease, or chronic infections. Chronic urticaria can significantly impact quality of life and may require comprehensive evaluation and management by a healthcare professional.\r\n\r\nTreatment for urticaria focuses on relieving symptoms and identifying and avoiding triggers. Antihistamines are the mainstay of treatment and can help reduce itching, redness, and swelling associated with hives. Non-sedating antihistamines are preferred for long-term management of chronic urticaria due to their efficacy and minimal side effects. In severe cases or when antihistamines alone are not effective, oral corticosteroids, immunosuppressants, or biologic therapies may be prescribed to control inflammation and symptoms.\r\n\r\nIn addition to medication, lifestyle modifications, such as avoiding known triggers, wearing loose-fitting clothing, and practicing stress-reduction techniques, may help prevent hives outbreaks and improve symptom control. If hives are accompanied by other symptoms, such as difficulty breathing, swelling of the face or throat, or dizziness, immediate medical attention is required, as these may indicate a severe allergic reaction or anaphylaxis. Overall, with proper management and avoidance of triggers, most cases of urticaria can be effectively controlled, allowing affected individuals to lead normal, symptom-free lives.', '', 'hives.jpeg.jpg'),
(21, 'Vascular Tumors', 'Vascular tumors are a diverse group of abnormal growths that arise from blood vessels or vascular structures within the body. These tumors can occur in various organs and tissues and may be benign or malignant. Vascular tumors are classified based on their histological features, clinical behavior, and underlying genetic mutations.\r\n\r\nOne common type of benign vascular tumor is hemangioma, which is characterized by an overgrowth of blood vessels. Hemangiomas can occur in infancy (infantile hemangiomas) or later in life (acquired hemangiomas) and may present as red or purplish growths on the skin or mucous membranes. While most hemangiomas are harmless and may spontaneously regress over time, some may cause complications, such as ulceration, bleeding, or compression of nearby structures, requiring medical intervention.\r\n\r\nOther types of benign vascular tumors include venous malformations, lymphatic malformations, and arteriovenous malformations. These tumors are typically present at birth and may manifest as abnormal clusters of blood vessels or lymphatic channels in various parts of the body. Although benign, vascular malformations can cause symptoms such as pain, swelling, or functional impairment, depending on their location and size.\r\n\r\nMalignant vascular tumors, such as angiosarcoma, are rare but aggressive cancers that arise from the endothelial cells lining blood vessels. Angiosarcoma can occur in the skin, soft tissues, or internal organs and tends to grow rapidly and metastasize to distant sites. Treatment for angiosarcoma may involve surgery, radiation therapy, chemotherapy, or targeted therapies, depending on the extent and stage of the disease.\r\n\r\nDiagnosis of vascular tumors often involves a combination of clinical evaluation, imaging studies (such as ultrasound, MRI, or CT scans), and histopathological examination of biopsy specimens. Management of vascular tumors depends on various factors, including the tumor type, size, location, and clinical presentation. Treatment strategies may include observation, medical therapy, minimally invasive procedures (such as embolization or sclerotherapy), or surgical resection, tailored to the individual patient\'s needs and the specific characteristics of the tumor.\r\n\r\nOverall, vascular tumors encompass a wide spectrum of benign and malignant growths that require careful evaluation and management by a multidisciplinary team of healthcare professionals, including dermatologists, oncologists, radiologists, and ', '', 'Vascular.jpeg.jpg'),
(22, 'Vasculitis ', 'Vasculitis is a group of rare autoimmune disorders characterized by inflammation of blood vessels, leading to tissue damage and impaired blood flow to organs and tissues throughout the body. Vasculitis can affect blood vessels of various sizes, including small vessels (small vessel vasculitis), medium-sized vessels (medium vessel vasculitis), and large vessels (large vessel vasculitis). The exact cause of vasculitis is often unknown, but it is believed to result from an abnormal immune response that leads to inflammation and damage to blood vessel walls.\r\n\r\nThe clinical presentation of vasculitis can vary widely depending on the size and location of the affected blood vessels. Common symptoms may include fever, fatigue, weight loss, muscle and joint pain, skin rash, nerve damage, and organ dysfunction. The severity of symptoms can range from mild to life-threatening, depending on the extent and severity of blood vessel involvement.\r\n\r\nThere are many different types of vasculitis, each with its own characteristic features and clinical manifestations. Examples of vasculitis include:\r\n\r\nGiant cell arteritis (temporal arteritis): Giant cell arteritis primarily affects medium and large arteries, particularly the temporal arteries in the head and neck. It is characterized by headache, scalp tenderness, jaw pain, visual disturbances, and, if left untreated, can lead to blindness or stroke.\r\n\r\nGranulomatosis with polyangiitis (Wegener\'s granulomatosis): Granulomatosis with polyangiitis is a form of small vessel vasculitis that primarily affects the upper and lower respiratory tract and kidneys. It is characterized by sinusitis, nasal ulcers, cough, shortness of breath, kidney dysfunction, and systemic symptoms such as fever and weight loss.\r\n\r\nMicroscopic polyangiitis: Microscopic polyangiitis is a small vessel vasculitis that affects the kidneys, lungs, and skin. It is characterized by kidney damage (glomerulonephritis), lung involvement (pulmonary hemorrhage), skin rash, joint pain, and peripheral neuropathy.\r\n\r\nTreatment for vasculitis depends on the type, severity, and extent of blood vessel involvement. Immunosuppressive medications, such as corticosteroids, methotrexate, cyclophosphamide, or rituximab, are often used to suppress inflammation and prevent further damage to blood vessels. In severe cases or when vital organs are affected, high-dose corticosteroids and immunosuppressive agents may be required to induce remission and prevent relapses. Early diagn', '', 'Vasculitis.jpeg.jpg'),
(23, 'Warts Molluscum', 'Viral infections affecting the skin can manifest in various forms, including warts, molluscum contagiosum, and other viral conditions. These infections are caused by different types of viruses and often present with characteristic clinical features.\r\n\r\nWarts, caused by the human papillomavirus (HPV), are common viral infections of the skin and mucous membranes. They appear as rough, raised growths on the skin, ranging in size from small, flat lesions to larger, cauliflower-like masses. Warts can occur on any part of the body but are most commonly found on the hands, feet (plantar warts), and genitals. Treatment options for warts include topical medications (such as salicylic acid or imiquimod), cryotherapy (freezing), laser therapy, or surgical removal.\r\n\r\nMolluscum contagiosum is a viral skin infection caused by the molluscum contagiosum virus (MCV), a member of the poxvirus family. It presents as small, flesh-colored or pearly papules with a central indentation (umbilication) on the skin or mucous membranes. Molluscum contagiosum lesions are typically painless but may be itchy or become inflamed. This infection is highly contagious and can spread through direct skin-to-skin contact or contact with contaminated objects. Treatment may include topical therapies (such as imiquimod or podophyllotoxin), cryotherapy, curettage (scraping), or laser therapy.\r\n\r\nOther viral infections of the skin include:\r\n\r\nHerpes simplex virus (HSV) infections: HSV infections can cause cold sores (herpes labialis) or genital herpes (herpes genitalis). These infections present as painful, fluid-filled blisters on the lips, mouth, or genital area. Antiviral medications, such as acyclovir, valacyclovir, or famciclovir, can help reduce the severity and duration of symptoms during outbreaks.\r\n\r\nChickenpox (varicella) and shingles (herpes zoster): Chickenpox is caused by the varicella-zoster virus (VZV) and presents as a rash of itchy, fluid-filled blisters on the skin. Shingles is a reactivation of the dormant VZV virus, typically occurring later in life, and manifests as a painful rash or blisters along a single dermatome. Vaccination against varicella and herpes zoster can prevent these infections or reduce their severity.\r\n\r\nHuman herpesvirus 6 (HHV-6) and HHV-7: These viruses are associated with roseola infantum, a common childhood illness characterized by high fever followed by a rash.\r\n\r\nViral infections of the skin can be uncomfortable, unsightly, and contagious, but most reso', '', 'Warts Molluscum.jpeg.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `docregister`
--

CREATE TABLE `docregister` (
  `id` int(11) NOT NULL,
  `name` varchar(300) NOT NULL,
  `email` varchar(300) NOT NULL,
  `phone` varchar(300) NOT NULL,
  `specialization` varchar(300) NOT NULL,
  `password` varchar(300) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `docregister`
--

INSERT INTO `docregister` (`id`, `name`, `email`, `phone`, `specialization`, `password`) VALUES
(2, 'allan', 'allansuttu@gmail.com', '', '', 'allan124');

-- --------------------------------------------------------

--
-- Table structure for table `feedback`
--

CREATE TABLE `feedback` (
  `id` int(11) NOT NULL,
  `name` varchar(111) NOT NULL,
  `mobile_no` varchar(111) NOT NULL,
  `rating` varchar(111) NOT NULL,
  `feedback` varchar(111) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `feedback`
--

INSERT INTO `feedback` (`id`, `name`, `mobile_no`, `rating`, `feedback`) VALUES
(11, 'ammu', '9632589635', '5.0', 'good'),
(12, '', '', '', ''),
(13, 'allan', '9874563210', '5.0', 'good');

-- --------------------------------------------------------

--
-- Table structure for table `hct`
--

CREATE TABLE `hct` (
  `id` int(11) NOT NULL,
  `name` varchar(300) NOT NULL,
  `details1` varchar(2500) NOT NULL,
  `details2` varchar(2500) NOT NULL,
  `img` varchar(2500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `hct`
--

INSERT INTO `hct` (`id`, `name`, `details1`, `details2`, `img`) VALUES
(1, 'Hydration: Drink plenty of water to keep your skin hydrated from the inside out.\r\n', 'Hydration is key for maintaining healthy skin. Drinking an adequate amount of water helps to keep the skin hydrated, which in turn can improve its elasticity, texture, and overall appearance. Water plays a vital role in various bodily functions, including flushing out toxins and delivering nutrients to the skin cells.', '', 'AcneRosacea.jpeg');

-- --------------------------------------------------------

--
-- Table structure for table `messages`
--

CREATE TABLE `messages` (
  `id` int(11) NOT NULL,
  `sender_id` int(11) NOT NULL,
  `receiver_id` int(11) NOT NULL,
  `sender_role` enum('doctor','patient') NOT NULL,
  `message` text NOT NULL,
  `timestamp` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `messages`
--

INSERT INTO `messages` (`id`, `sender_id`, `receiver_id`, `sender_role`, `message`, `timestamp`) VALUES
(1, 3, 2, 'patient', 'hi', '2024-04-26 02:36:09'),
(2, 3, 2, 'patient', 'hello', '2024-04-26 02:38:10'),
(3, 3, 2, 'patient', 'how are you?', '2024-04-26 02:39:34'),
(4, 3, 2, 'patient', 'where are you from?', '2024-04-26 02:40:33'),
(5, 2, 3, 'doctor', 'good', '2024-04-26 03:34:43'),
(6, 2, 3, 'doctor', 'helloooo ☺️', '2024-04-26 03:39:48'),
(7, 3, 2, 'patient', 'ok', '2024-04-26 03:41:50'),
(8, 5, 2, 'patient', 'heeei', '2024-04-26 03:44:05'),
(9, 5, 2, 'patient', 'how r u?', '2024-04-26 03:44:16'),
(10, 7, 2, 'patient', 'Hii', '2024-04-26 15:48:17'),
(11, 7, 2, 'patient', 'I have acne on my face', '2024-04-26 15:48:41'),
(12, 2, 7, 'doctor', 'ok', '2024-04-26 15:49:07'),
(13, 2, 7, 'doctor', 'let me check', '2024-04-26 15:49:13');

-- --------------------------------------------------------

--
-- Table structure for table `register`
--

CREATE TABLE `register` (
  `id` int(11) NOT NULL,
  `name` varchar(300) NOT NULL,
  `address` varchar(300) NOT NULL,
  `email` varchar(300) NOT NULL,
  `phonenumber` varchar(300) NOT NULL,
  `height` varchar(300) NOT NULL,
  `weight` varchar(300) NOT NULL,
  `age` varchar(300) NOT NULL,
  `gender` varchar(300) NOT NULL,
  `password` varchar(300) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `register`
--

INSERT INTO `register` (`id`, `name`, `address`, `email`, `phonenumber`, `height`, `weight`, `age`, `gender`, `password`) VALUES
(1, '', '', '', '', '', '', '', '', ''),
(2, 'gopika', 'addressaddress ', 'gopika@gmail.com', '9632589635', '58', '96', '20', 'Female', '963963'),
(3, 'ammu', 'addressaddress ', 'ammu@gamil.com', '9632589632', '50', 'ammuammu', '6', 'Female', 'ammuammu'),
(4, 'appu', 'addressaddress ', 'appu@gmail.com', '9632589632', '654', '50', '59', 'Male', 'appuappu123'),
(5, 'anu', 'addressaddress ', 'anu@gmail.com', '9632589635', '2', '586', '28', 'Male', 'anuanu'),
(6, 'sree', 'addressaddress ', 'sree@gmail.com', '9632587456', '369', '96', '5', 'Male', '12345678'),
(7, 'allan', 'qeryio', 'allangeo@gmail.com', '9874563210', '168', '69', '20', 'Male', 'allan123'),
(8, 'ammu', 'addressaddress', 'ammu@gmail.com', '9632589635', '21', '25', '25', 'Female', 'ammuammu');

-- --------------------------------------------------------

--
-- Table structure for table `upload`
--

CREATE TABLE `upload` (
  `id` int(11) NOT NULL,
  `name` varchar(300) NOT NULL,
  `phonenumber` varchar(300) NOT NULL,
  `img` varchar(2500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `upload`
--

INSERT INTO `upload` (`id`, `name`, `phonenumber`, `img`) VALUES
(1, 'allan', '9874563210', 'IMG-20240320-WA0028.jpeg'),
(2, 'ammu', '9632589632', 'IMG-20240320-WA0018.jpg'),
(3, 'allan', '9874563210', 'IMG-20240320-WA0007.jpg'),
(4, 'allan', '9874563210', '1000024535.jpg'),
(5, 'allan', '9874563210', '1000024562.jpg'),
(6, 'allan', '9874563210', '1000024784.jpg'),
(7, 'allan', '9874563210', '1000020910.jpg'),
(8, 'allan', '9874563210', '1000025277.jpg'),
(9, 'allan', '9874563210', '1000025617.heic'),
(10, 'allan', '9874563210', '1000025617.heic'),
(11, 'allan', '9874563210', '1000025679.jpg'),
(12, 'allan', '9874563210', '1000084229.jpg'),
(13, 'allan', '9874563210', '1000084381.jpg'),
(14, 'allan', '9874563210', '1000084573.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `blogs`
--
ALTER TABLE `blogs`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `docregister`
--
ALTER TABLE `docregister`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `feedback`
--
ALTER TABLE `feedback`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `hct`
--
ALTER TABLE `hct`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `messages`
--
ALTER TABLE `messages`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `register`
--
ALTER TABLE `register`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `upload`
--
ALTER TABLE `upload`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `blogs`
--
ALTER TABLE `blogs`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=24;

--
-- AUTO_INCREMENT for table `docregister`
--
ALTER TABLE `docregister`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--
-- AUTO_INCREMENT for table `feedback`
--
ALTER TABLE `feedback`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;

--
-- AUTO_INCREMENT for table `hct`
--
ALTER TABLE `hct`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `messages`
--
ALTER TABLE `messages`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;

--
-- AUTO_INCREMENT for table `register`
--
ALTER TABLE `register`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

--
-- AUTO_INCREMENT for table `upload`
--
ALTER TABLE `upload`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=15;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
